BEGIN TRANSACTION;;
CREATE TABLE exercises (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  display_name_pt TEXT NOT NULL,
  category TEXT,
  notes TEXT
);;
INSERT INTO "exercises" VALUES(1,'abdominal_bicicleta','Abdominal Bicicleta',NULL,NULL);;
INSERT INTO "exercises" VALUES(2,'abdominal_crunch','Abdominal Crunch',NULL,NULL);;
INSERT INTO "exercises" VALUES(3,'abdominal_crunch_haltere','Abdominal Crunch Haltere',NULL,NULL);;
INSERT INTO "exercises" VALUES(4,'abdominal_maquina','Abdominal Maquina',NULL,NULL);;
INSERT INTO "exercises" VALUES(5,'abdominal_obliquo_solo','Abdominal Obliquo Solo',NULL,NULL);;
INSERT INTO "exercises" VALUES(6,'abdominal_russo','Abdominal Russo',NULL,NULL);;
INSERT INTO "exercises" VALUES(7,'abdominal_russo_com_halteres','Abdominal Russo Com Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(8,'abdominal_stomach_vacuum','Abdominal Stomach Vacuum',NULL,NULL);;
INSERT INTO "exercises" VALUES(9,'abdominal_supino_solo','Abdominal Supino Solo',NULL,NULL);;
INSERT INTO "exercises" VALUES(10,'abdominal_twist_russo','Abdominal Twist Russo',NULL,NULL);;
INSERT INTO "exercises" VALUES(11,'afundo_bulgaro_com_haltere','Afundo Bulgaro Com Haltere',NULL,NULL);;
INSERT INTO "exercises" VALUES(12,'afundo_halteres','Afundo Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(13,'agachamento_com_barra','Agachamento Com Barra',NULL,NULL);;
INSERT INTO "exercises" VALUES(14,'agachamento_com_salto','Agachamento Com Salto',NULL,NULL);;
INSERT INTO "exercises" VALUES(15,'agachamento_costas_barra','Agachamento Costas Barra',NULL,NULL);;
INSERT INTO "exercises" VALUES(16,'agachamento_goblet','Agachamento Goblet',NULL,NULL);;
INSERT INTO "exercises" VALUES(17,'agachamento_isometrico','Agachamento Isometrico',NULL,NULL);;
INSERT INTO "exercises" VALUES(18,'agachamento_sumo_haltere','Agachamento Sumo Haltere',NULL,NULL);;
INSERT INTO "exercises" VALUES(19,'alpinista','Alpinista',NULL,NULL);;
INSERT INTO "exercises" VALUES(20,'alpinista_mountain_climber','Alpinista Mountain Climber',NULL,NULL);;
INSERT INTO "exercises" VALUES(21,'avanco_alternado','Avanco Alternado',NULL,NULL);;
INSERT INTO "exercises" VALUES(22,'barra_fixa_pronada','Barra Fixa Pronada',NULL,NULL);;
INSERT INTO "exercises" VALUES(23,'burpee','Burpee',NULL,NULL);;
INSERT INTO "exercises" VALUES(24,'cadeira_abdutora','Cadeira Abdutora',NULL,NULL);;
INSERT INTO "exercises" VALUES(25,'cadeira_adutora','Cadeira Adutora',NULL,NULL);;
INSERT INTO "exercises" VALUES(26,'cadeira_extensora','Cadeira Extensora',NULL,NULL);;
INSERT INTO "exercises" VALUES(27,'cadeira_flexora','Cadeira Flexora',NULL,NULL);;
INSERT INTO "exercises" VALUES(28,'caminhada_esteira','Caminhada Esteira',NULL,NULL);;
INSERT INTO "exercises" VALUES(29,'caminhada_na_esteira','Caminhada Na Esteira',NULL,NULL);;
INSERT INTO "exercises" VALUES(30,'corrida_esteira_inclinada','Corrida Esteira Inclinada',NULL,NULL);;
INSERT INTO "exercises" VALUES(31,'corrida_na_esteira','Corrida Na Esteira',NULL,NULL);;
INSERT INTO "exercises" VALUES(32,'crucifixo_halteres_reto','Crucifixo Halteres Reto',NULL,NULL);;
INSERT INTO "exercises" VALUES(33,'crucifixo_horizontal_halteres','Crucifixo Horizontal Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(34,'crucifixo_polia_media','Crucifixo Polia Media',NULL,NULL);;
INSERT INTO "exercises" VALUES(35,'dead_bug','Dead Bug',NULL,NULL);;
INSERT INTO "exercises" VALUES(36,'desenvolvimento_arnold','Desenvolvimento Arnold',NULL,NULL);;
INSERT INTO "exercises" VALUES(37,'desenvolvimento_arnold_halteres','Desenvolvimento Arnold Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(38,'desenvolvimento_halteres','Desenvolvimento Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(39,'desenvolvimento_maquina','Desenvolvimento Maquina',NULL,NULL);;
INSERT INTO "exercises" VALUES(40,'desenvolvimento_ombros_halteres','Desenvolvimento Ombros Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(41,'desenvolvimento_sentado_com_halteres','Desenvolvimento Sentado Com Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(42,'elevacao_lateral_com_halteres','Elevacao Lateral Com Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(43,'elevacao_lateral_ombros','Elevacao Lateral Ombros',NULL,NULL);;
INSERT INTO "exercises" VALUES(44,'elevacao_pelvica_haltere','Elevacao Pelvica Haltere',NULL,NULL);;
INSERT INTO "exercises" VALUES(45,'elevacao_frontal_halteres','Elevacao Frontal Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(46,'elevacao_lateral_e_frontal_halteres','Elevacao Lateral E Frontal Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(47,'elevacao_lateral_halteres','Elevacao Lateral Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(48,'elevacao_pelvica_com_anilha','Elevacao Pelvica Com Anilha',NULL,NULL);;
INSERT INTO "exercises" VALUES(49,'elevacao_pelvica_solo','Elevacao Pelvica Solo',NULL,NULL);;
INSERT INTO "exercises" VALUES(50,'encolhimento_halteres','Encolhimento Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(51,'escada_ergometrica','Escada Ergometrica',NULL,NULL);;
INSERT INTO "exercises" VALUES(52,'face_pull_corda','Face Pull Corda',NULL,NULL);;
INSERT INTO "exercises" VALUES(53,'flexao_de_bracos','Flexao De Bracos',NULL,NULL);;
INSERT INTO "exercises" VALUES(54,'flexao_de_bracos_ajoelhada','Flexao De Bracos Ajoelhada',NULL,NULL);;
INSERT INTO "exercises" VALUES(55,'flexao_de_bracos_com_joelhos','Flexao De Bracos Com Joelhos',NULL,NULL);;
INSERT INTO "exercises" VALUES(56,'flexao_de_bracos_declinada','Flexao De Bracos Declinada',NULL,NULL);;
INSERT INTO "exercises" VALUES(57,'flexao_de_bracos_diamante','Flexao De Bracos Diamante',NULL,NULL);;
INSERT INTO "exercises" VALUES(58,'flexao_de_bracos_inclinada','Flexao De Bracos Inclinada',NULL,NULL);;
INSERT INTO "exercises" VALUES(59,'flexao_de_bracos_na_parede','Flexao De Bracos Na Parede',NULL,NULL);;
INSERT INTO "exercises" VALUES(60,'flexao_de_bracos_solo','Flexao De Bracos Solo',NULL,NULL);;
INSERT INTO "exercises" VALUES(61,'flexao_de_bracos_tradicional','Flexao De Bracos Tradicional',NULL,NULL);;
INSERT INTO "exercises" VALUES(62,'flexao_diamante','Flexao Diamante',NULL,NULL);;
INSERT INTO "exercises" VALUES(63,'flexao_pike','Flexao Pike',NULL,NULL);;
INSERT INTO "exercises" VALUES(64,'flexao_de_pernas_maquina_sentado','Flexao De Pernas Maquina Sentado',NULL,NULL);;
INSERT INTO "exercises" VALUES(65,'kettlebell_swing','Kettlebell Swing',NULL,NULL);;
INSERT INTO "exercises" VALUES(66,'leg_press_45','Leg Press 45',NULL,NULL);;
INSERT INTO "exercises" VALUES(67,'leg_press_45_horizontal','Leg Press 45 Horizontal',NULL,NULL);;
INSERT INTO "exercises" VALUES(68,'leg_press_45_inclinado','Leg Press 45 Inclinado',NULL,NULL);;
INSERT INTO "exercises" VALUES(69,'leg_press_maquina','Leg Press Maquina',NULL,NULL);;
INSERT INTO "exercises" VALUES(70,'mesa_flexora','Mesa Flexora',NULL,NULL);;
INSERT INTO "exercises" VALUES(71,'panturrilha_em_pe','Panturrilha Em Pe',NULL,NULL);;
INSERT INTO "exercises" VALUES(72,'peck_deck','Peck Deck',NULL,NULL);;
INSERT INTO "exercises" VALUES(73,'polichinelo','Polichinelo',NULL,NULL);;
INSERT INTO "exercises" VALUES(74,'polichinelo_frontal','Polichinelo Frontal',NULL,NULL);;
INSERT INTO "exercises" VALUES(75,'polichinelo_tradicional','Polichinelo Tradicional',NULL,NULL);;
INSERT INTO "exercises" VALUES(76,'prancha_abdominal','Prancha Abdominal',NULL,NULL);;
INSERT INTO "exercises" VALUES(77,'pull_down_corda','Pull Down Corda',NULL,NULL);;
INSERT INTO "exercises" VALUES(78,'puxada_frente_polia_alta','Puxada Frente Polia Alta',NULL,NULL);;
INSERT INTO "exercises" VALUES(79,'puxada_unilateral_polia','Puxada Unilateral Polia',NULL,NULL);;
INSERT INTO "exercises" VALUES(80,'remada_baixa_polia','Remada Baixa Polia',NULL,NULL);;
INSERT INTO "exercises" VALUES(81,'remada_curvada_barra','Remada Curvada Barra',NULL,NULL);;
INSERT INTO "exercises" VALUES(82,'remada_curvada_halteres','Remada Curvada Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(83,'remada_curvada_halteres_pronada','Remada Curvada Halteres Pronada',NULL,NULL);;
INSERT INTO "exercises" VALUES(84,'remada_maquina_remo','Remada Maquina Remo',NULL,NULL);;
INSERT INTO "exercises" VALUES(85,'remada_maquina_sentado','Remada Maquina Sentado',NULL,NULL);;
INSERT INTO "exercises" VALUES(86,'remada_sentada_maquina','Remada Sentada Maquina',NULL,NULL);;
INSERT INTO "exercises" VALUES(87,'remada_unilateral_com_haltere','Remada Unilateral Com Haltere',NULL,NULL);;
INSERT INTO "exercises" VALUES(88,'remada_unilateral_halteres','Remada Unilateral Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(89,'rosca_biceps_corda_polia_baixa','Rosca Biceps Corda Polia Baixa',NULL,NULL);;
INSERT INTO "exercises" VALUES(90,'rosca_biceps_na_polia_baixa','Rosca Biceps Na Polia Baixa',NULL,NULL);;
INSERT INTO "exercises" VALUES(91,'rosca_concentrada_halteres','Rosca Concentrada Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(92,'rosca_direta_barra','Rosca Direta Barra',NULL,NULL);;
INSERT INTO "exercises" VALUES(93,'rosca_direta_halteres','Rosca Direta Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(94,'rosca_martelo_alternada','Rosca Martelo Alternada',NULL,NULL);;
INSERT INTO "exercises" VALUES(95,'rosca_martelo_alternada_halteres','Rosca Martelo Alternada Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(96,'rosca_martelo_halteres','Rosca Martelo Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(97,'stiff_com_barra','Stiff Com Barra',NULL,NULL);;
INSERT INTO "exercises" VALUES(98,'stiff_com_halteres','Stiff Com Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(99,'stiff_deadlift_halteres','Stiff Deadlift Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(100,'supino_articulado_maquina','Supino Articulado Maquina',NULL,NULL);;
INSERT INTO "exercises" VALUES(101,'supino_barra_reto','Supino Barra Reto',NULL,NULL);;
INSERT INTO "exercises" VALUES(102,'supino_fechado_com_halteres','Supino Fechado Com Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(103,'supino_fechado_halteres','Supino Fechado Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(104,'supino_halteres_reto','Supino Halteres Reto',NULL,NULL);;
INSERT INTO "exercises" VALUES(105,'supino_inclinado_articulado_maquina','Supino Inclinado Articulado Maquina',NULL,NULL);;
INSERT INTO "exercises" VALUES(106,'supino_inclinado_barra','Supino Inclinado Barra',NULL,NULL);;
INSERT INTO "exercises" VALUES(107,'supino_inclinado_com_halteres','Supino Inclinado Com Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(108,'supino_inclinado_halteres','Supino Inclinado Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(109,'supino_maquina','Supino Maquina',NULL,NULL);;
INSERT INTO "exercises" VALUES(110,'supino_reto_barra','Supino Reto Barra',NULL,NULL);;
INSERT INTO "exercises" VALUES(111,'supino_reto_halteres','Supino Reto Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(112,'triceps_banco','Triceps Banco',NULL,NULL);;
INSERT INTO "exercises" VALUES(113,'triceps_coice_com_halteres','Triceps Coice Com Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(114,'triceps_coice_halteres','Triceps Coice Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(115,'triceps_corda','Triceps Corda',NULL,NULL);;
INSERT INTO "exercises" VALUES(116,'triceps_corda_costas_polia_baixa','Triceps Corda Costas Polia Baixa',NULL,NULL);;
INSERT INTO "exercises" VALUES(117,'triceps_corda_polia','Triceps Corda Polia',NULL,NULL);;
INSERT INTO "exercises" VALUES(118,'triceps_corda_polia_alta','Triceps Corda Polia Alta',NULL,NULL);;
INSERT INTO "exercises" VALUES(119,'triceps_frances_barra_supino','Triceps Frances Barra Supino',NULL,NULL);;
INSERT INTO "exercises" VALUES(120,'triceps_frances_haltere','Triceps Frances Haltere',NULL,NULL);;
INSERT INTO "exercises" VALUES(121,'triceps_frances_halteres_solo','Triceps Frances Halteres Solo',NULL,NULL);;
INSERT INTO "exercises" VALUES(122,'triceps_frances_sentado_com_halteres','Triceps Frances Sentado Com Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(123,'triceps_frances_unilateral_halteres','Triceps Frances Unilateral Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(124,'triceps_kickback_haltere','Triceps Kickback Haltere',NULL,NULL);;
INSERT INTO "exercises" VALUES(125,'triceps_mergulho_solo','Triceps Mergulho Solo',NULL,NULL);;
INSERT INTO "exercises" VALUES(126,'triceps_pulley_corda','Triceps Pulley Corda',NULL,NULL);;
INSERT INTO "exercises" VALUES(127,'triceps_pulley_pronada','Triceps Pulley Pronada',NULL,NULL);;
INSERT INTO "exercises" VALUES(128,'triceps_pulley_v','Triceps Pulley V',NULL,NULL);;
INSERT INTO "exercises" VALUES(129,'triceps_solo','Triceps Solo',NULL,NULL);;
INSERT INTO "exercises" VALUES(130,'triceps_testa_halteres','Triceps Testa Halteres',NULL,NULL);;
INSERT INTO "exercises" VALUES(131,'voador_maquina','Voador Maquina',NULL,NULL);;
CREATE TABLE videos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  exercise_slug TEXT NOT NULL,
  file_name TEXT NOT NULL,
  variant INTEGER NOT NULL DEFAULT 1,
  gender TEXT NOT NULL CHECK(gender IN ('male','female','unisex','review_required')),
  duration_sec REAL,
  width INTEGER,
  height INTEGER,
  firebase_path TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ready',
  FOREIGN KEY(exercise_slug) REFERENCES exercises(slug)
);;
INSERT INTO "videos" VALUES(1,'abdominal_bicicleta','abdominal_bicicleta (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/abdominal_bicicleta/abdominal_bicicleta (2).mp4','ready');;
INSERT INTO "videos" VALUES(2,'abdominal_bicicleta','abdominal_bicicleta.mp4',1,'review_required',0.0,NULL,NULL,'exercises/abdominal_bicicleta/abdominal_bicicleta.mp4','ready');;
INSERT INTO "videos" VALUES(3,'abdominal_crunch','abdominal_crunch.mp4',1,'unisex',0.0,NULL,NULL,'exercises/abdominal_crunch/abdominal_crunch.mp4','ready');;
INSERT INTO "videos" VALUES(4,'abdominal_crunch_haltere','abdominal_crunch_haltere.mp4',1,'unisex',0.0,NULL,NULL,'exercises/abdominal_crunch_haltere/abdominal_crunch_haltere.mp4','ready');;
INSERT INTO "videos" VALUES(5,'abdominal_maquina','abdominal_maquina.mp4',1,'unisex',0.0,NULL,NULL,'exercises/abdominal_maquina/abdominal_maquina.mp4','ready');;
INSERT INTO "videos" VALUES(6,'abdominal_obliquo_solo','abdominal_obliquo_solo.mp4',1,'unisex',0.0,NULL,NULL,'exercises/abdominal_obliquo_solo/abdominal_obliquo_solo.mp4','ready');;
INSERT INTO "videos" VALUES(7,'abdominal_russo','abdominal_russo.mp4',1,'unisex',0.0,NULL,NULL,'exercises/abdominal_russo/abdominal_russo.mp4','ready');;
INSERT INTO "videos" VALUES(8,'abdominal_russo_com_halteres','abdominal_russo_com_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/abdominal_russo_com_halteres/abdominal_russo_com_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(9,'abdominal_stomach_vacuum','abdominal_stomach_vacuum.mp4',1,'unisex',0.0,NULL,NULL,'exercises/abdominal_stomach_vacuum/abdominal_stomach_vacuum.mp4','ready');;
INSERT INTO "videos" VALUES(10,'abdominal_supino_solo','abdominal_supino_solo.mp4',1,'unisex',0.0,NULL,NULL,'exercises/abdominal_supino_solo/abdominal_supino_solo.mp4','ready');;
INSERT INTO "videos" VALUES(11,'abdominal_twist_russo','abdominal_twist_russo.mp4',1,'unisex',0.0,NULL,NULL,'exercises/abdominal_twist_russo/abdominal_twist_russo.mp4','ready');;
INSERT INTO "videos" VALUES(12,'afundo_bulgaro_com_haltere','afundo_bulgaro_com_haltere.mp4',1,'unisex',0.0,NULL,NULL,'exercises/afundo_bulgaro_com_haltere/afundo_bulgaro_com_haltere.mp4','ready');;
INSERT INTO "videos" VALUES(13,'afundo_halteres','afundo_halteres (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/afundo_halteres/afundo_halteres (2).mp4','ready');;
INSERT INTO "videos" VALUES(14,'afundo_halteres','afundo_halteres.mp4',1,'review_required',0.0,NULL,NULL,'exercises/afundo_halteres/afundo_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(15,'agachamento_com_barra','agachamento_com_barra.mp4',1,'unisex',0.0,NULL,NULL,'exercises/agachamento_com_barra/agachamento_com_barra.mp4','ready');;
INSERT INTO "videos" VALUES(16,'agachamento_com_salto','agachamento_com_salto.mp4',1,'unisex',0.0,NULL,NULL,'exercises/agachamento_com_salto/agachamento_com_salto.mp4','ready');;
INSERT INTO "videos" VALUES(17,'agachamento_costas_barra','agachamento_costas_barra.mp4',1,'unisex',0.0,NULL,NULL,'exercises/agachamento_costas_barra/agachamento_costas_barra.mp4','ready');;
INSERT INTO "videos" VALUES(18,'agachamento_goblet','agachamento_goblet (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/agachamento_goblet/agachamento_goblet (2).mp4','ready');;
INSERT INTO "videos" VALUES(19,'agachamento_goblet','agachamento_goblet.mp4',1,'review_required',0.0,NULL,NULL,'exercises/agachamento_goblet/agachamento_goblet.mp4','ready');;
INSERT INTO "videos" VALUES(20,'agachamento_isometrico','agachamento_isométrico.mp4',1,'unisex',0.0,NULL,NULL,'exercises/agachamento_isometrico/agachamento_isométrico.mp4','ready');;
INSERT INTO "videos" VALUES(21,'agachamento_sumo_haltere','agachamento_sumo_haltere (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/agachamento_sumo_haltere/agachamento_sumo_haltere (2).mp4','ready');;
INSERT INTO "videos" VALUES(22,'agachamento_sumo_haltere','agachamento_sumo_haltere.mp4',1,'review_required',0.0,NULL,NULL,'exercises/agachamento_sumo_haltere/agachamento_sumo_haltere.mp4','ready');;
INSERT INTO "videos" VALUES(23,'alpinista','alpinista.mp4',1,'unisex',0.0,NULL,NULL,'exercises/alpinista/alpinista.mp4','ready');;
INSERT INTO "videos" VALUES(24,'alpinista_mountain_climber','alpinista_mountain_climber.mp4',1,'unisex',0.0,NULL,NULL,'exercises/alpinista_mountain_climber/alpinista_mountain_climber.mp4','ready');;
INSERT INTO "videos" VALUES(25,'avanco_alternado','avanco_alternado.mp4',1,'unisex',0.0,NULL,NULL,'exercises/avanco_alternado/avanco_alternado.mp4','ready');;
INSERT INTO "videos" VALUES(26,'barra_fixa_pronada','barra_fixa_pronada.mp4',1,'unisex',0.0,NULL,NULL,'exercises/barra_fixa_pronada/barra_fixa_pronada.mp4','ready');;
INSERT INTO "videos" VALUES(27,'burpee','burpee (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/burpee/burpee (2).mp4','ready');;
INSERT INTO "videos" VALUES(28,'burpee','burpee.mp4',1,'review_required',0.0,NULL,NULL,'exercises/burpee/burpee.mp4','ready');;
INSERT INTO "videos" VALUES(29,'cadeira_abdutora','cadeira_abdutora.mp4',1,'unisex',0.0,NULL,NULL,'exercises/cadeira_abdutora/cadeira_abdutora.mp4','ready');;
INSERT INTO "videos" VALUES(30,'cadeira_adutora','cadeira_adutora.mp4',1,'unisex',0.0,NULL,NULL,'exercises/cadeira_adutora/cadeira_adutora.mp4','ready');;
INSERT INTO "videos" VALUES(31,'cadeira_extensora','cadeira_extensora (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/cadeira_extensora/cadeira_extensora (2).mp4','ready');;
INSERT INTO "videos" VALUES(32,'cadeira_extensora','cadeira_extensora.mp4',1,'review_required',0.0,NULL,NULL,'exercises/cadeira_extensora/cadeira_extensora.mp4','ready');;
INSERT INTO "videos" VALUES(33,'cadeira_flexora','cadeira_flexora.mp4',1,'unisex',0.0,NULL,NULL,'exercises/cadeira_flexora/cadeira_flexora.mp4','ready');;
INSERT INTO "videos" VALUES(34,'caminhada_esteira','caminhada_esteira.mp4',1,'unisex',0.0,NULL,NULL,'exercises/caminhada_esteira/caminhada_esteira.mp4','ready');;
INSERT INTO "videos" VALUES(35,'caminhada_na_esteira','caminhada_na_esteira.mp4',1,'unisex',0.0,NULL,NULL,'exercises/caminhada_na_esteira/caminhada_na_esteira.mp4','ready');;
INSERT INTO "videos" VALUES(36,'corrida_esteira_inclinada','corrida_esteira_inclinada.mp4',1,'unisex',0.0,NULL,NULL,'exercises/corrida_esteira_inclinada/corrida_esteira_inclinada.mp4','ready');;
INSERT INTO "videos" VALUES(37,'corrida_na_esteira','corrida_na_esteira (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/corrida_na_esteira/corrida_na_esteira (2).mp4','ready');;
INSERT INTO "videos" VALUES(38,'corrida_na_esteira','corrida_na_esteira.mp4',1,'review_required',0.0,NULL,NULL,'exercises/corrida_na_esteira/corrida_na_esteira.mp4','ready');;
INSERT INTO "videos" VALUES(39,'crucifixo_halteres_reto','crucifixo_halteres_reto.mp4',1,'unisex',0.0,NULL,NULL,'exercises/crucifixo_halteres_reto/crucifixo_halteres_reto.mp4','ready');;
INSERT INTO "videos" VALUES(40,'crucifixo_horizontal_halteres','crucifixo_horizontal_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/crucifixo_horizontal_halteres/crucifixo_horizontal_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(41,'crucifixo_polia_media','crucifixo_polia_media.mp4',1,'unisex',0.0,NULL,NULL,'exercises/crucifixo_polia_media/crucifixo_polia_media.mp4','ready');;
INSERT INTO "videos" VALUES(42,'dead_bug','dead_bug.mp4',1,'unisex',0.0,NULL,NULL,'exercises/dead_bug/dead_bug.mp4','ready');;
INSERT INTO "videos" VALUES(43,'desenvolvimento_arnold','desenvolvimento_arnold.mp4',1,'unisex',0.0,NULL,NULL,'exercises/desenvolvimento_arnold/desenvolvimento_arnold.mp4','ready');;
INSERT INTO "videos" VALUES(44,'desenvolvimento_arnold_halteres','desenvolvimento_arnold_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/desenvolvimento_arnold_halteres/desenvolvimento_arnold_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(45,'desenvolvimento_halteres','desenvolvimento_halteres (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/desenvolvimento_halteres/desenvolvimento_halteres (2).mp4','ready');;
INSERT INTO "videos" VALUES(46,'desenvolvimento_halteres','desenvolvimento_halteres.mp4',1,'review_required',0.0,NULL,NULL,'exercises/desenvolvimento_halteres/desenvolvimento_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(47,'desenvolvimento_maquina','desenvolvimento_maquina (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/desenvolvimento_maquina/desenvolvimento_maquina (2).mp4','ready');;
INSERT INTO "videos" VALUES(48,'desenvolvimento_maquina','desenvolvimento_maquina.mp4',1,'review_required',0.0,NULL,NULL,'exercises/desenvolvimento_maquina/desenvolvimento_maquina.mp4','ready');;
INSERT INTO "videos" VALUES(49,'desenvolvimento_ombros_halteres','desenvolvimento_ombros_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/desenvolvimento_ombros_halteres/desenvolvimento_ombros_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(50,'desenvolvimento_sentado_com_halteres','desenvolvimento_sentado_com_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/desenvolvimento_sentado_com_halteres/desenvolvimento_sentado_com_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(51,'elevacao_lateral_com_halteres','elevacao_lateral_com_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/elevacao_lateral_com_halteres/elevacao_lateral_com_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(52,'elevacao_lateral_ombros','elevacao_lateral_ombros.mp4',1,'unisex',0.0,NULL,NULL,'exercises/elevacao_lateral_ombros/elevacao_lateral_ombros.mp4','ready');;
INSERT INTO "videos" VALUES(53,'elevacao_pelvica_haltere','elevacao_pelvica_haltere.mp4',1,'unisex',0.0,NULL,NULL,'exercises/elevacao_pelvica_haltere/elevacao_pelvica_haltere.mp4','ready');;
INSERT INTO "videos" VALUES(54,'elevacao_frontal_halteres','elevaçao_frontal_halteres.mp4',1,'review_required',0.0,NULL,NULL,'exercises/elevacao_frontal_halteres/elevaçao_frontal_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(55,'elevacao_lateral_e_frontal_halteres','elevaçao_lateral_e_frontal_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/elevacao_lateral_e_frontal_halteres/elevaçao_lateral_e_frontal_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(56,'elevacao_lateral_halteres','elevaçao_lateral_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/elevacao_lateral_halteres/elevaçao_lateral_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(57,'elevacao_frontal_halteres','elevação_frontal_halteres.mp4',1,'review_required',0.0,NULL,NULL,'exercises/elevacao_frontal_halteres/elevação_frontal_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(58,'elevacao_pelvica_com_anilha','elevação_pélvica_com_anilha.mp4',1,'unisex',0.0,NULL,NULL,'exercises/elevacao_pelvica_com_anilha/elevação_pélvica_com_anilha.mp4','ready');;
INSERT INTO "videos" VALUES(59,'elevacao_pelvica_solo','elevação_pélvica_solo.mp4',1,'unisex',0.0,NULL,NULL,'exercises/elevacao_pelvica_solo/elevação_pélvica_solo.mp4','ready');;
INSERT INTO "videos" VALUES(60,'encolhimento_halteres','encolhimento_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/encolhimento_halteres/encolhimento_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(61,'escada_ergometrica','escada_ergometrica.mp4',1,'unisex',0.0,NULL,NULL,'exercises/escada_ergometrica/escada_ergometrica.mp4','ready');;
INSERT INTO "videos" VALUES(62,'face_pull_corda','face_pull_corda.mp4',1,'unisex',0.0,NULL,NULL,'exercises/face_pull_corda/face_pull_corda.mp4','ready');;
INSERT INTO "videos" VALUES(63,'flexao_de_bracos','flexao_de_bracos (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/flexao_de_bracos/flexao_de_bracos (2).mp4','ready');;
INSERT INTO "videos" VALUES(64,'flexao_de_bracos','flexao_de_bracos.mp4',1,'review_required',0.0,NULL,NULL,'exercises/flexao_de_bracos/flexao_de_bracos.mp4','ready');;
INSERT INTO "videos" VALUES(65,'flexao_de_bracos_ajoelhada','flexao_de_bracos_ajoelhada.mp4',1,'unisex',0.0,NULL,NULL,'exercises/flexao_de_bracos_ajoelhada/flexao_de_bracos_ajoelhada.mp4','ready');;
INSERT INTO "videos" VALUES(66,'flexao_de_bracos_com_joelhos','flexao_de_bracos_com_joelhos.mp4',1,'unisex',0.0,NULL,NULL,'exercises/flexao_de_bracos_com_joelhos/flexao_de_bracos_com_joelhos.mp4','ready');;
INSERT INTO "videos" VALUES(67,'flexao_de_bracos_declinada','flexao_de_bracos_declinada.mp4',1,'unisex',0.0,NULL,NULL,'exercises/flexao_de_bracos_declinada/flexao_de_bracos_declinada.mp4','ready');;
INSERT INTO "videos" VALUES(68,'flexao_de_bracos_diamante','flexao_de_bracos_diamante.mp4',1,'unisex',0.0,NULL,NULL,'exercises/flexao_de_bracos_diamante/flexao_de_bracos_diamante.mp4','ready');;
INSERT INTO "videos" VALUES(69,'flexao_de_bracos_inclinada','flexao_de_bracos_inclinada (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/flexao_de_bracos_inclinada/flexao_de_bracos_inclinada (2).mp4','ready');;
INSERT INTO "videos" VALUES(70,'flexao_de_bracos_inclinada','flexao_de_bracos_inclinada.mp4',1,'review_required',0.0,NULL,NULL,'exercises/flexao_de_bracos_inclinada/flexao_de_bracos_inclinada.mp4','ready');;
INSERT INTO "videos" VALUES(71,'flexao_de_bracos_na_parede','flexao_de_bracos_na_parede (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/flexao_de_bracos_na_parede/flexao_de_bracos_na_parede (2).mp4','ready');;
INSERT INTO "videos" VALUES(72,'flexao_de_bracos_na_parede','flexao_de_bracos_na_parede.mp4',1,'review_required',0.0,NULL,NULL,'exercises/flexao_de_bracos_na_parede/flexao_de_bracos_na_parede.mp4','ready');;
INSERT INTO "videos" VALUES(73,'flexao_de_bracos_solo','flexao_de_bracos_solo (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/flexao_de_bracos_solo/flexao_de_bracos_solo (2).mp4','ready');;
INSERT INTO "videos" VALUES(74,'flexao_de_bracos_solo','flexao_de_bracos_solo (3).mp4',3,'review_required',0.0,NULL,NULL,'exercises/flexao_de_bracos_solo/flexao_de_bracos_solo (3).mp4','ready');;
INSERT INTO "videos" VALUES(75,'flexao_de_bracos_solo','flexao_de_bracos_solo.mp4',1,'review_required',0.0,NULL,NULL,'exercises/flexao_de_bracos_solo/flexao_de_bracos_solo.mp4','ready');;
INSERT INTO "videos" VALUES(76,'flexao_de_bracos_tradicional','flexao_de_bracos_tradicional.mp4',1,'unisex',0.0,NULL,NULL,'exercises/flexao_de_bracos_tradicional/flexao_de_bracos_tradicional.mp4','ready');;
INSERT INTO "videos" VALUES(77,'flexao_diamante','flexao_diamante.mp4',1,'unisex',0.0,NULL,NULL,'exercises/flexao_diamante/flexao_diamante.mp4','ready');;
INSERT INTO "videos" VALUES(78,'flexao_pike','flexao_pike.mp4',1,'unisex',0.0,NULL,NULL,'exercises/flexao_pike/flexao_pike.mp4','ready');;
INSERT INTO "videos" VALUES(79,'flexao_de_pernas_maquina_sentado','flexão_de_pernas_maquina_sentado.mp4',1,'unisex',0.0,NULL,NULL,'exercises/flexao_de_pernas_maquina_sentado/flexão_de_pernas_maquina_sentado.mp4','ready');;
INSERT INTO "videos" VALUES(80,'kettlebell_swing','kettlebell_swing.mp4',1,'unisex',0.0,NULL,NULL,'exercises/kettlebell_swing/kettlebell_swing.mp4','ready');;
INSERT INTO "videos" VALUES(81,'leg_press_45','leg_press_45.mp4',1,'unisex',0.0,NULL,NULL,'exercises/leg_press_45/leg_press_45.mp4','ready');;
INSERT INTO "videos" VALUES(82,'leg_press_45_horizontal','leg_press_45_horizontal.mp4',1,'unisex',0.0,NULL,NULL,'exercises/leg_press_45_horizontal/leg_press_45_horizontal.mp4','ready');;
INSERT INTO "videos" VALUES(83,'leg_press_45_inclinado','leg_press_45_inclinado.mp4',1,'unisex',0.0,NULL,NULL,'exercises/leg_press_45_inclinado/leg_press_45_inclinado.mp4','ready');;
INSERT INTO "videos" VALUES(84,'leg_press_maquina','leg_press_maquina.mp4',1,'unisex',0.0,NULL,NULL,'exercises/leg_press_maquina/leg_press_maquina.mp4','ready');;
INSERT INTO "videos" VALUES(85,'mesa_flexora','mesa_flexora.mp4',1,'unisex',0.0,NULL,NULL,'exercises/mesa_flexora/mesa_flexora.mp4','ready');;
INSERT INTO "videos" VALUES(86,'panturrilha_em_pe','panturrilha_em_pe.mp4',1,'unisex',0.0,NULL,NULL,'exercises/panturrilha_em_pe/panturrilha_em_pe.mp4','ready');;
INSERT INTO "videos" VALUES(87,'peck_deck','peck_deck.mp4',1,'unisex',0.0,NULL,NULL,'exercises/peck_deck/peck_deck.mp4','ready');;
INSERT INTO "videos" VALUES(88,'polichinelo','polichinelo.mp4',1,'unisex',0.0,NULL,NULL,'exercises/polichinelo/polichinelo.mp4','ready');;
INSERT INTO "videos" VALUES(89,'polichinelo_frontal','polichinelo_frontal.mp4',1,'unisex',0.0,NULL,NULL,'exercises/polichinelo_frontal/polichinelo_frontal.mp4','ready');;
INSERT INTO "videos" VALUES(90,'polichinelo_tradicional','polichinelo_tradicional.mp4',1,'unisex',0.0,NULL,NULL,'exercises/polichinelo_tradicional/polichinelo_tradicional.mp4','ready');;
INSERT INTO "videos" VALUES(91,'prancha_abdominal','prancha_abdominal (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/prancha_abdominal/prancha_abdominal (2).mp4','ready');;
INSERT INTO "videos" VALUES(92,'prancha_abdominal','prancha_abdominal.mp4',1,'review_required',0.0,NULL,NULL,'exercises/prancha_abdominal/prancha_abdominal.mp4','ready');;
INSERT INTO "videos" VALUES(93,'pull_down_corda','pull_down_corda.mp4',1,'unisex',0.0,NULL,NULL,'exercises/pull_down_corda/pull_down_corda.mp4','ready');;
INSERT INTO "videos" VALUES(94,'puxada_frente_polia_alta','puxada_frente_polia_alta (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/puxada_frente_polia_alta/puxada_frente_polia_alta (2).mp4','ready');;
INSERT INTO "videos" VALUES(95,'puxada_frente_polia_alta','puxada_frente_polia_alta.mp4',1,'review_required',0.0,NULL,NULL,'exercises/puxada_frente_polia_alta/puxada_frente_polia_alta.mp4','ready');;
INSERT INTO "videos" VALUES(96,'puxada_unilateral_polia','puxada_unilateral_polia (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/puxada_unilateral_polia/puxada_unilateral_polia (2).mp4','ready');;
INSERT INTO "videos" VALUES(97,'puxada_unilateral_polia','puxada_unilateral_polia.mp4',1,'review_required',0.0,NULL,NULL,'exercises/puxada_unilateral_polia/puxada_unilateral_polia.mp4','ready');;
INSERT INTO "videos" VALUES(98,'remada_baixa_polia','remada_baixa_polia (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/remada_baixa_polia/remada_baixa_polia (2).mp4','ready');;
INSERT INTO "videos" VALUES(99,'remada_baixa_polia','remada_baixa_polia.mp4',1,'review_required',0.0,NULL,NULL,'exercises/remada_baixa_polia/remada_baixa_polia.mp4','ready');;
INSERT INTO "videos" VALUES(100,'remada_curvada_barra','remada_curvada_barra (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/remada_curvada_barra/remada_curvada_barra (2).mp4','ready');;
INSERT INTO "videos" VALUES(101,'remada_curvada_barra','remada_curvada_barra.mp4',1,'review_required',0.0,NULL,NULL,'exercises/remada_curvada_barra/remada_curvada_barra.mp4','ready');;
INSERT INTO "videos" VALUES(102,'remada_curvada_halteres','remada_curvada_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/remada_curvada_halteres/remada_curvada_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(103,'remada_curvada_halteres_pronada','remada_curvada_halteres_pronada.mp4',1,'unisex',0.0,NULL,NULL,'exercises/remada_curvada_halteres_pronada/remada_curvada_halteres_pronada.mp4','ready');;
INSERT INTO "videos" VALUES(104,'remada_maquina_remo','remada_maquina_remo.mp4',1,'unisex',0.0,NULL,NULL,'exercises/remada_maquina_remo/remada_maquina_remo.mp4','ready');;
INSERT INTO "videos" VALUES(105,'remada_maquina_sentado','remada_maquina_sentado.mp4',1,'unisex',0.0,NULL,NULL,'exercises/remada_maquina_sentado/remada_maquina_sentado.mp4','ready');;
INSERT INTO "videos" VALUES(106,'remada_sentada_maquina','remada_sentada_maquina.mp4',1,'unisex',0.0,NULL,NULL,'exercises/remada_sentada_maquina/remada_sentada_maquina.mp4','ready');;
INSERT INTO "videos" VALUES(107,'remada_unilateral_com_haltere','remada_unilateral_com_haltere.mp4',1,'unisex',0.0,NULL,NULL,'exercises/remada_unilateral_com_haltere/remada_unilateral_com_haltere.mp4','ready');;
INSERT INTO "videos" VALUES(108,'remada_unilateral_halteres','remada_unilateral_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/remada_unilateral_halteres/remada_unilateral_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(109,'rosca_biceps_corda_polia_baixa','rosca_biceps_corda_polia_baixa.mp4',1,'unisex',0.0,NULL,NULL,'exercises/rosca_biceps_corda_polia_baixa/rosca_biceps_corda_polia_baixa.mp4','ready');;
INSERT INTO "videos" VALUES(110,'rosca_biceps_na_polia_baixa','rosca_bíceps_na_polia_baixa.mp4',1,'unisex',0.0,NULL,NULL,'exercises/rosca_biceps_na_polia_baixa/rosca_bíceps_na_polia_baixa.mp4','ready');;
INSERT INTO "videos" VALUES(111,'rosca_concentrada_halteres','rosca_concentrada_halteres (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/rosca_concentrada_halteres/rosca_concentrada_halteres (2).mp4','ready');;
INSERT INTO "videos" VALUES(112,'rosca_concentrada_halteres','rosca_concentrada_halteres.mp4',1,'review_required',0.0,NULL,NULL,'exercises/rosca_concentrada_halteres/rosca_concentrada_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(113,'rosca_direta_barra','rosca_direta_barra.mp4',1,'unisex',0.0,NULL,NULL,'exercises/rosca_direta_barra/rosca_direta_barra.mp4','ready');;
INSERT INTO "videos" VALUES(114,'rosca_direta_halteres','rosca_direta_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/rosca_direta_halteres/rosca_direta_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(115,'rosca_martelo_alternada','rosca_martelo_alternada.mp4',1,'unisex',0.0,NULL,NULL,'exercises/rosca_martelo_alternada/rosca_martelo_alternada.mp4','ready');;
INSERT INTO "videos" VALUES(116,'rosca_martelo_alternada_halteres','rosca_martelo_alternada_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/rosca_martelo_alternada_halteres/rosca_martelo_alternada_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(117,'rosca_martelo_halteres','rosca_martelo_halteres (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/rosca_martelo_halteres/rosca_martelo_halteres (2).mp4','ready');;
INSERT INTO "videos" VALUES(118,'rosca_martelo_halteres','rosca_martelo_halteres (3).mp4',3,'review_required',0.0,NULL,NULL,'exercises/rosca_martelo_halteres/rosca_martelo_halteres (3).mp4','ready');;
INSERT INTO "videos" VALUES(119,'rosca_martelo_halteres','rosca_martelo_halteres.mp4',1,'review_required',0.0,NULL,NULL,'exercises/rosca_martelo_halteres/rosca_martelo_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(120,'stiff_com_barra','stiff_com_barra.mp4',1,'unisex',0.0,NULL,NULL,'exercises/stiff_com_barra/stiff_com_barra.mp4','ready');;
INSERT INTO "videos" VALUES(121,'stiff_com_halteres','stiff_com_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/stiff_com_halteres/stiff_com_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(122,'stiff_deadlift_halteres','stiff_deadlift_halteres (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/stiff_deadlift_halteres/stiff_deadlift_halteres (2).mp4','ready');;
INSERT INTO "videos" VALUES(123,'stiff_deadlift_halteres','stiff_deadlift_halteres.mp4',1,'review_required',0.0,NULL,NULL,'exercises/stiff_deadlift_halteres/stiff_deadlift_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(124,'supino_articulado_maquina','supino_articulado_maquina.mp4',1,'unisex',0.0,NULL,NULL,'exercises/supino_articulado_maquina/supino_articulado_maquina.mp4','ready');;
INSERT INTO "videos" VALUES(125,'supino_barra_reto','supino_barra_reto.mp4',1,'unisex',0.0,NULL,NULL,'exercises/supino_barra_reto/supino_barra_reto.mp4','ready');;
INSERT INTO "videos" VALUES(126,'supino_fechado_com_halteres','supino_fechado_com_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/supino_fechado_com_halteres/supino_fechado_com_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(127,'supino_fechado_halteres','supino_fechado_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/supino_fechado_halteres/supino_fechado_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(128,'supino_halteres_reto','supino_halteres_reto.mp4',1,'unisex',0.0,NULL,NULL,'exercises/supino_halteres_reto/supino_halteres_reto.mp4','ready');;
INSERT INTO "videos" VALUES(129,'supino_inclinado_articulado_maquina','supino_inclinado_articulado_maquina.mp4',1,'unisex',0.0,NULL,NULL,'exercises/supino_inclinado_articulado_maquina/supino_inclinado_articulado_maquina.mp4','ready');;
INSERT INTO "videos" VALUES(130,'supino_inclinado_barra','supino_inclinado_barra.mp4',1,'unisex',0.0,NULL,NULL,'exercises/supino_inclinado_barra/supino_inclinado_barra.mp4','ready');;
INSERT INTO "videos" VALUES(131,'supino_inclinado_com_halteres','supino_inclinado_com_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/supino_inclinado_com_halteres/supino_inclinado_com_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(132,'supino_inclinado_halteres','supino_inclinado_halteres (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/supino_inclinado_halteres/supino_inclinado_halteres (2).mp4','ready');;
INSERT INTO "videos" VALUES(133,'supino_inclinado_halteres','supino_inclinado_halteres.mp4',1,'review_required',0.0,NULL,NULL,'exercises/supino_inclinado_halteres/supino_inclinado_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(134,'supino_maquina','supino_maquina.mp4',1,'unisex',0.0,NULL,NULL,'exercises/supino_maquina/supino_maquina.mp4','ready');;
INSERT INTO "videos" VALUES(135,'supino_reto_barra','supino_reto_barra.mp4',1,'unisex',0.0,NULL,NULL,'exercises/supino_reto_barra/supino_reto_barra.mp4','ready');;
INSERT INTO "videos" VALUES(136,'supino_reto_halteres','supino_reto_halteres (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/supino_reto_halteres/supino_reto_halteres (2).mp4','ready');;
INSERT INTO "videos" VALUES(137,'supino_reto_halteres','supino_reto_halteres.mp4',1,'review_required',0.0,NULL,NULL,'exercises/supino_reto_halteres/supino_reto_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(138,'triceps_banco','triceps_banco (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/triceps_banco/triceps_banco (2).mp4','ready');;
INSERT INTO "videos" VALUES(139,'triceps_banco','triceps_banco (3).mp4',3,'review_required',0.0,NULL,NULL,'exercises/triceps_banco/triceps_banco (3).mp4','ready');;
INSERT INTO "videos" VALUES(140,'triceps_banco','triceps_banco.mp4',1,'review_required',0.0,NULL,NULL,'exercises/triceps_banco/triceps_banco.mp4','ready');;
INSERT INTO "videos" VALUES(141,'triceps_coice_com_halteres','triceps_coice_com_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_coice_com_halteres/triceps_coice_com_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(142,'triceps_coice_halteres','triceps_coice_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_coice_halteres/triceps_coice_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(143,'triceps_corda','triceps_corda.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_corda/triceps_corda.mp4','ready');;
INSERT INTO "videos" VALUES(144,'triceps_corda_costas_polia_baixa','triceps_corda_costas_polia_baixa.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_corda_costas_polia_baixa/triceps_corda_costas_polia_baixa.mp4','ready');;
INSERT INTO "videos" VALUES(145,'triceps_corda_polia','triceps_corda_polia.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_corda_polia/triceps_corda_polia.mp4','ready');;
INSERT INTO "videos" VALUES(146,'triceps_corda_polia_alta','triceps_corda_polia_alta.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_corda_polia_alta/triceps_corda_polia_alta.mp4','ready');;
INSERT INTO "videos" VALUES(147,'triceps_frances_barra_supino','triceps_frances_barra_supino.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_frances_barra_supino/triceps_frances_barra_supino.mp4','ready');;
INSERT INTO "videos" VALUES(148,'triceps_frances_haltere','triceps_frances_haltere.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_frances_haltere/triceps_frances_haltere.mp4','ready');;
INSERT INTO "videos" VALUES(149,'triceps_frances_halteres_solo','triceps_frances_halteres_solo.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_frances_halteres_solo/triceps_frances_halteres_solo.mp4','ready');;
INSERT INTO "videos" VALUES(150,'triceps_frances_sentado_com_halteres','triceps_frances_sentado_com_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_frances_sentado_com_halteres/triceps_frances_sentado_com_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(151,'triceps_frances_unilateral_halteres','triceps_frances_unilateral_halteres.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_frances_unilateral_halteres/triceps_frances_unilateral_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(152,'triceps_kickback_haltere','triceps_kickback_haltere.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_kickback_haltere/triceps_kickback_haltere.mp4','ready');;
INSERT INTO "videos" VALUES(153,'triceps_mergulho_solo','triceps_mergulho_solo.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_mergulho_solo/triceps_mergulho_solo.mp4','ready');;
INSERT INTO "videos" VALUES(154,'triceps_pulley_corda','triceps_pulley_corda.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_pulley_corda/triceps_pulley_corda.mp4','ready');;
INSERT INTO "videos" VALUES(155,'triceps_pulley_pronada','triceps_pulley_pronada.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_pulley_pronada/triceps_pulley_pronada.mp4','ready');;
INSERT INTO "videos" VALUES(156,'triceps_pulley_v','triceps_pulley_v.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_pulley_v/triceps_pulley_v.mp4','ready');;
INSERT INTO "videos" VALUES(157,'triceps_solo','triceps_solo.mp4',1,'unisex',0.0,NULL,NULL,'exercises/triceps_solo/triceps_solo.mp4','ready');;
INSERT INTO "videos" VALUES(158,'triceps_testa_halteres','triceps_testa_halteres (2).mp4',2,'review_required',0.0,NULL,NULL,'exercises/triceps_testa_halteres/triceps_testa_halteres (2).mp4','ready');;
INSERT INTO "videos" VALUES(159,'triceps_testa_halteres','triceps_testa_halteres.mp4',1,'review_required',0.0,NULL,NULL,'exercises/triceps_testa_halteres/triceps_testa_halteres.mp4','ready');;
INSERT INTO "videos" VALUES(160,'voador_maquina','voador_maquina.mp4',1,'unisex',0.0,NULL,NULL,'exercises/voador_maquina/voador_maquina.mp4','ready');;
CREATE INDEX idx_videos_slug ON videos(exercise_slug);;
CREATE INDEX idx_videos_gender ON videos(gender);;
DELETE FROM "sqlite_sequence";;
INSERT INTO "sqlite_sequence" VALUES('exercises',131);;
INSERT INTO "sqlite_sequence" VALUES('videos',160);;
COMMIT;;
